# Default values for dws-frontend-app
# These can be overridden by environment-specific values

app:
  name: dws-event-frontend
  replicas: 1
  apiUrl: "http://dws-event-service.dws-event-service.svc.cluster.local:80/api/v1/events"
  nodeEnv: "production"

namespace: dws-frontend

domain: frontend.ltu-m7011e-6.se

email: leakle-5@student.ltu.se

environment: Default

image:
  repository: ghcr.io/dws-org/dws-event-frontend
  tag: latest
  pullSecret: ghcr-secret

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

ingress:
  certIssuer: letsencrypt-staging
